/* ═══════════════════════════════════════════════════════════
   THE METHOD MAFIA — ভেতরের পেজগুলোর অনুবাদ
   Payment / Order Status / About / Terms / Privacy / Refund
   English · বাংলা · हिन्दी
   ═══════════════════════════════════════════════════════════ */

const PAGES = {

/* ─────────────── ENGLISH ─────────────── */
en: {
  back:"Back to home",

  /* ── PAYMENT ── */
  payTitle:"Payment Instructions",
  paySub:"How to complete your membership payment",
  payNote:"<strong>Important:</strong> We do not display payment details publicly, to protect both you and us from fraud. Everything is shared directly on Telegram after you place your order.",
  payH1:"How It Works",
  payS1t:"Place your order",
  payS1d:"Fill in the order form on our homepage with your name, email and Telegram username. You will receive an Order ID.",
  payS2t:"Message us on Telegram",
  payS2d:"After submitting, you will be redirected to our support account. Send us your Order ID and we will reply with the current payment details.",
  payS3t:"Make the payment",
  payS3d:"Send the amount using whichever method you selected. Take a screenshot of the transaction as proof.",
  payS4t:"Send us the proof",
  payS4d:"Share the screenshot and your transaction ID on Telegram. We verify every payment manually.",
  payS5t:"Receive your access",
  payS5d:"Once confirmed, we send you a private one-time invite link. This usually takes 30 minutes to 3 hours.",
  payH2:"Accepted Payment Methods",
  payH3:"Pricing",
  payEntry:"Entry (first month):",
  payMonthly:"Monthly (from second month):",
  payH4:"Important Notes",
  payN1:"Only send payment to the details we give you on Telegram. Never trust numbers shared by anyone else.",
  payN2:"Keep your transaction ID until your access is confirmed.",
  payN3:"Your Telegram username must be correct, or we cannot send the invite.",
  payN4:"We never ask for your PIN, OTP or password. Anyone who does is a scammer.",
  payHelp:"Need help? Message us at",
  payCta:"Place Your Order",

  /* ── ORDER STATUS ── */
  ordTitle:"Order Status",
  ordSub:"Check where your order stands",
  ordFind:"Find Your Order",
  ordFindSub:"Enter the Order ID you received",
  ordLbl:"Order ID",
  ordBtn:"Check Status",
  ordH1:"What The Statuses Mean",
  ordSt1:"<strong>Pending</strong> — We have your order but have not received or confirmed payment yet.",
  ordSt2:"<strong>Verifying</strong> — We received your payment proof and are checking it.",
  ordSt3:"<strong>Active</strong> — Payment confirmed and your invite link has been sent on Telegram.",
  ordSt4:"<strong>Expired</strong> — Your membership period has ended. Renew to regain access.",
  ordH2:"Lost Your Order ID?",
  ordLost:"No problem. Message us on Telegram with the email address or Telegram username you used when ordering, and we will find it for you.",
  ordHelp:"For any order issue, contact",
  ordHelp2:"— we usually reply within a few hours.",
  ordErr:"Please enter your Order ID.",
  ordFound:"Order found:",
  ordStatus:"Status:",
  ordSubmitted:"Submitted",
  ordFoundMsg:"Your order was received. To confirm payment and get your access link, message us on Telegram with this Order ID.",
  ordNF:"We could not verify this Order ID from this device.",
  ordNF2:"Please message us on Telegram with your Order ID and we will check it manually.",

  /* ── ABOUT ── */
  abTitle:"About Us",
  abSub:"Who we are and why we built this",
  abH1:"Our Story",
  abP1:"The Method Mafia started the way most useful things do — out of frustration.",
  abP2:"We were spending hundreds of dollars a month on software subscriptions before earning anything back. Courses that promised the world cost more than many people earn in a month, and half of them repeated the same tired basics. The genuinely useful information was scattered across YouTube comments, forgotten blog posts and private groups you had to know someone to get into.",
  abP3:"So we started collecting. Every method that actually worked, every tool worth using, every guide that taught something real — we saved it, tested it and organised it.",
  abP4:"What began as a personal archive became a community. Today over 56,000 people follow us across Telegram and Facebook, and thousands have joined our premium library.",
  abH2:"What We Believe",
  abB1:"<strong>Access should not be a privilege.</strong> Where you live should not decide whether you can afford to learn.",
  abB2:"<strong>Quality over quantity.</strong> Every method is tested before it goes into the group.",
  abB3:"<strong>No false promises.</strong> We do not promise overnight riches. We give you methods and tools — the work is still yours.",
  abB4:"<strong>Community first.</strong> The people inside are what make this worth joining.",
  abH3:"What We Are Not",
  abNP:"We want to be honest about this, because a lot of people in this space are not.",
  abN1:"We are not a get-rich-quick scheme.",
  abN2:"We do not guarantee any income. Anyone who does is lying to you.",
  abN3:"We are not a replacement for effort. The library is a starting point, not a finish line.",
  abH4:"By The Numbers",
  abNum1:"<strong>30,000+</strong> Facebook followers",
  abNum2:"<strong>26,000+</strong> public Telegram members",
  abNum3:"<strong>2,900+</strong> active premium members",
  abNum4:"<strong>1,000+</strong> curated methods, tools and guides",
  abNum5:"<strong>50-70+</strong> new resources added every month",
  abH5:"Get In Touch",
  abGet:"We read everything. If you have a question, a suggestion or a complaint, we want to hear it.",
  abBox:"Not ready to join yet? That is completely fine. Start with our free public channel and see whether what we share is useful to you. No payment, no commitment.",
  abCta:"Join Our Free Channel",
  abFree:"Free Channel:",
  abFb:"Facebook:",
  abTg:"Telegram:",
  abMail:"Email:",

  /* ── TERMS ── */
  tmTitle:"Terms &amp; Conditions",
  tmSub:"Last updated: August 2026",
  tmH1:"1. Agreement",
  tmP1:"By accessing this website or purchasing a membership, you agree to these terms. If you do not agree, please do not use our service.",
  tmH2:"2. What We Provide",
  tmP2:"The Method Mafia is a digital resource and learning community. Membership gives you access to a private Telegram channel containing curated methods, tools, guides and educational material.",
  tmP2b:"We provide access to information and resources. We do not provide the third-party services themselves, and we are not affiliated with, endorsed by, or partnered with any third-party brand mentioned in our material.",
  tmH3:"3. Membership &amp; Billing",
  tmB1:"Entry fee covers your first month of access.",
  tmB2:"From the second month onwards, a monthly fee applies to maintain access.",
  tmB3:"Membership is not automatically renewed. You pay each period manually.",
  tmB4:"If payment is not received, access ends when the paid period expires.",
  tmB5:"Prices may change. Existing members are notified before any change affects them.",
  tmH4:"4. Your Responsibilities",
  tmP4:"You agree that you will:",
  tmC1:"Provide accurate information when ordering",
  tmC2:"Keep your access link private and not share it with others",
  tmC3:"Not redistribute or republish our content without written permission",
  tmC4:"Not use our material for any unlawful purpose",
  tmC5:"Treat other members and staff respectfully",
  tmH5:"5. Account Termination",
  tmP5:"We may remove your access without refund if you:",
  tmD1:"Share your access link or content with non-members",
  tmD2:"Attempt to resell our material without authorisation",
  tmD3:"Harass other members or staff",
  tmD4:"Use the community for spam or fraudulent activity",
  tmH6:"6. No Income Guarantee",
  tmP6:"We make no promise, guarantee or representation about any income, profit or business result. Any examples shared are illustrative only and are not typical. Your results depend entirely on your own effort, skill, market conditions and other factors outside our control.",
  tmH7:"7. Third-Party Services",
  tmP7:"Our material may reference or discuss third-party platforms and tools. Your use of any third-party service is governed by that service's own terms. You are responsible for complying with them. We are not liable for anything that happens through your use of third-party services.",
  tmH8:"8. Intellectual Property",
  tmP8:"All original content, branding, design and material we create belongs to The Method Mafia. You may use it for your own learning but may not reproduce or distribute it commercially.",
  tmH9:"9. Limitation of Liability",
  tmP9:"Our service is provided as is. To the maximum extent permitted by law, we are not liable for any indirect, incidental or consequential damages arising from your use of our service. Our total liability is limited to the amount you paid us in the previous three months.",
  tmH10:"10. Changes To These Terms",
  tmP10:"We may update these terms. Material changes will be announced in our channels. Continued use after changes means you accept the updated terms.",
  tmH11:"11. Governing Law",
  tmP11:"These terms are governed by the laws of Bangladesh.",
  tmH12:"12. Contact",
  tmP12:"Questions about these terms? Email",
  tmP12b:"or message",
  tmP12c:"on Telegram.",

  /* ── PRIVACY ── */
  prTitle:"Privacy Policy",
  prSub:"Last updated: August 2026",
  prH1:"1. Introduction",
  prP1:"This policy explains what information we collect, why we collect it and what we do with it. We keep this deliberately short and plain because you should actually be able to read it.",
  prH2:"2. What We Collect",
  prP2a:"<strong>Information you give us:</strong>",
  prG1:"Name",
  prG2:"Email address",
  prG3:"Telegram username",
  prG4:"Payment reference or transaction ID (when you send proof of payment)",
  prP2b:"<strong>Information collected automatically:</strong>",
  prA1:"Pages visited and time spent",
  prA2:"Approximate location (country or city level)",
  prA3:"Device and browser type",
  prA4:"Referral source, including advertising campaign parameters",
  prH3:"3. Why We Collect It",
  prW1:"To process your order and give you access",
  prW2:"To contact you about your membership",
  prW3:"To send renewal reminders",
  prW4:"To understand which marketing works so we spend our budget sensibly",
  prW5:"To improve the site and the service",
  prH5:"4. What We Do Not Do",
  prN1:"We do not sell your personal information to anyone.",
  prN2:"We do not share your data with other members.",
  prN3:"We do not store your payment credentials, PIN, OTP or card details. We never ask for them.",
  prN4:"We do not send unsolicited marketing to people who have not contacted us.",
  prH6:"5. How Long We Keep Data",
  prP6:"Order records are kept for as long as your membership is active and for a reasonable period afterwards for accounting purposes. You can request deletion at any time.",
  prH7:"6. Your Rights",
  prP7:"You can ask us to:",
  prR1:"Show you what data we hold about you",
  prR2:"Correct anything that is wrong",
  prR3:"Delete your data",
  prR4:"Stop sending you messages",
  prP7b:"To make any of these requests, email",
  prH8:"7. Cookies",
  prP8:"We use cookies and similar technologies for analytics and advertising measurement. You can disable cookies in your browser settings, though some parts of the site may not work as expected.",
  prH9:"8. Security",
  prP9:"We use HTTPS encryption and keep access to order data limited. No system is perfectly secure, but we take reasonable steps to protect your information.",
  prH10:"9. Children",
  prP10:"Our service is not intended for anyone under 18. We do not knowingly collect information from minors.",
  prH11:"10. Changes",
  prP11:"If we change this policy in a way that matters, we will announce it in our channels.",
  prH12:"11. Contact",
  prP12:"Privacy questions? Email",
  prP12b:"or message",

  /* ── REFUND ── */
  rfTitle:"Refund Policy",
  rfSub:"Last updated: August 2026",
  rfShort:"<strong>Short version:</strong> If something goes wrong on our side, we refund you. If you simply changed your mind after accessing the library, we generally cannot — because digital content cannot be returned once seen.",
  rfH1:"1. When You Get A Full Refund",
  rfP1:"We refund your payment in full if:",
  rfY1:"You paid but never received your access link, and we cannot resolve it within 48 hours",
  rfY2:"You were charged twice for the same period",
  rfY3:"You paid the wrong amount by mistake and have not yet accessed the channel",
  rfY4:"Our service becomes permanently unavailable during a period you have paid for",
  rfH2:"2. When We Cannot Refund",
  rfP2:"We are unable to refund if:",
  rfN1:"You have already joined the channel and viewed the content",
  rfN2:"You changed your mind after gaining access",
  rfN3:"You expected specific income results that did not happen",
  rfN4:"Your access was removed because you broke our terms",
  rfN5:"A third-party service you learned about stopped working — we do not control those services",
  rfN6:"More than 7 days have passed since payment",
  rfP2b:"This is standard for digital products. Once the library has been seen, it cannot be unseen.",
  rfH3:"3. Partial Refunds",
  rfP3:"If a genuine problem arises mid-period, we may offer a partial refund or extend your membership instead. We look at each case individually and try to be fair.",
  rfH4:"4. How To Request A Refund",
  rfS1:"Message us on Telegram within 7 days of payment",
  rfS2:"Include your Order ID",
  rfS3:"Explain what went wrong",
  rfS4:"Attach your payment proof",
  rfH5:"5. Processing Time",
  rfT1:"<strong>Review:</strong> within 48 hours of your request",
  rfT2:"<strong>Approved refunds:</strong> sent within 3 to 7 working days",
  rfT3:"<strong>Method:</strong> refunded to the same account you paid from",
  rfH6:"6. Cancelling Your Membership",
  rfP6:"There is nothing to cancel. Membership does not renew automatically — if you do not pay for the next month, your access simply ends when the current period expires. No cancellation fee, no notice required.",
  rfH7:"7. Chargebacks",
  rfP7:"Please talk to us before filing a chargeback or dispute. Most problems are a misunderstanding we can fix in minutes. Filing a dispute without contacting us first will result in permanent removal from the community.",
  rfH8:"8. Our Commitment",
  rfP8:"We would rather refund an unhappy customer than keep money that leaves a bad taste. If you feel genuinely misled, tell us. We will listen.",
  rfBox:"Questions about this policy? Message",
  rfBox2:"or email"
},

/* ─────────────── বাংলা ─────────────── */
bn: {
  back:"হোমে ফিরে যান",

  /* ── PAYMENT ── */
  payTitle:"পেমেন্ট নির্দেশনা",
  paySub:"মেম্বারশিপের পেমেন্ট কীভাবে সম্পন্ন করবেন",
  payNote:"<strong>গুরুত্বপূর্ণ:</strong> প্রতারণা থেকে আপনাকে ও আমাদের রক্ষা করতে পেমেন্টের তথ্য আমরা প্রকাশ্যে দিই না। অর্ডার করার পর সবকিছু সরাসরি টেলিগ্রামে জানানো হয়।",
  payH1:"যেভাবে কাজ করে",
  payS1t:"অর্ডার করুন",
  payS1d:"হোমপেজের ফর্মে আপনার নাম, ইমেইল ও টেলিগ্রাম ইউজারনেম দিন। একটি অর্ডার আইডি পাবেন।",
  payS2t:"টেলিগ্রামে মেসেজ করুন",
  payS2d:"সাবমিট করার পর আপনি আমাদের সাপোর্ট অ্যাকাউন্টে চলে যাবেন। অর্ডার আইডি পাঠান, আমরা পেমেন্টের বিস্তারিত জানিয়ে দেব।",
  payS3t:"পেমেন্ট করুন",
  payS3d:"আপনি যে মেথড বেছে নিয়েছেন সেটা দিয়ে টাকা পাঠান। লেনদেনের একটি স্ক্রিনশট রাখুন।",
  payS4t:"প্রমাণ পাঠান",
  payS4d:"স্ক্রিনশট ও ট্রানজেকশন আইডি টেলিগ্রামে পাঠান। প্রতিটি পেমেন্ট আমরা নিজে যাচাই করি।",
  payS5t:"অ্যাক্সেস পান",
  payS5d:"যাচাই হয়ে গেলে একটি ব্যক্তিগত ওয়ান-টাইম ইনভাইট লিংক পাঠাই। সাধারণত ৩০ মিনিট থেকে ৩ ঘণ্টা লাগে।",
  payH2:"যেসব পেমেন্ট মেথড নেওয়া হয়",
  payH3:"মূল্য",
  payEntry:"এন্ট্রি (প্রথম মাস):",
  payMonthly:"মাসিক (দ্বিতীয় মাস থেকে):",
  payH4:"গুরুত্বপূর্ণ কিছু কথা",
  payN1:"শুধু আমরা টেলিগ্রামে যে তথ্য দেব সেখানেই পেমেন্ট করবেন। অন্য কারো দেওয়া নম্বর কখনো বিশ্বাস করবেন না।",
  payN2:"অ্যাক্সেস নিশ্চিত না হওয়া পর্যন্ত ট্রানজেকশন আইডি সংরক্ষণ করুন।",
  payN3:"টেলিগ্রাম ইউজারনেম সঠিক হতে হবে, না হলে ইনভাইট পাঠানো যাবে না।",
  payN4:"আমরা কখনো আপনার পিন, ওটিপি বা পাসওয়ার্ড চাই না। যে চায়, সে প্রতারক।",
  payHelp:"সাহায্য দরকার? মেসেজ করুন",
  payCta:"অর্ডার করুন",

  /* ── ORDER STATUS ── */
  ordTitle:"অর্ডার স্ট্যাটাস",
  ordSub:"আপনার অর্ডার কোন অবস্থায় আছে দেখুন",
  ordFind:"আপনার অর্ডার খুঁজুন",
  ordFindSub:"আপনি যে অর্ডার আইডি পেয়েছেন সেটি দিন",
  ordLbl:"অর্ডার আইডি",
  ordBtn:"স্ট্যাটাস দেখুন",
  ordH1:"স্ট্যাটাসগুলোর অর্থ",
  ordSt1:"<strong>Pending</strong> — অর্ডার পেয়েছি, কিন্তু পেমেন্ট এখনো পাইনি বা যাচাই হয়নি।",
  ordSt2:"<strong>Verifying</strong> — পেমেন্টের প্রমাণ পেয়েছি, যাচাই করা হচ্ছে।",
  ordSt3:"<strong>Active</strong> — পেমেন্ট নিশ্চিত, টেলিগ্রামে ইনভাইট লিংক পাঠানো হয়েছে।",
  ordSt4:"<strong>Expired</strong> — মেম্বারশিপের মেয়াদ শেষ। আবার অ্যাক্সেস পেতে রিনিউ করুন।",
  ordH2:"অর্ডার আইডি হারিয়ে ফেলেছেন?",
  ordLost:"সমস্যা নেই। অর্ডার করার সময় যে ইমেইল বা টেলিগ্রাম ইউজারনেম দিয়েছিলেন সেটা টেলিগ্রামে পাঠান, আমরা খুঁজে দেব।",
  ordHelp:"অর্ডার সংক্রান্ত যেকোনো সমস্যায় যোগাযোগ করুন",
  ordHelp2:"— সাধারণত কয়েক ঘণ্টার মধ্যে উত্তর দিই।",
  ordErr:"অনুগ্রহ করে আপনার অর্ডার আইডি লিখুন।",
  ordFound:"অর্ডার পাওয়া গেছে:",
  ordStatus:"স্ট্যাটাস:",
  ordSubmitted:"সাবমিট হয়েছে",
  ordFoundMsg:"আপনার অর্ডার পেয়েছি। পেমেন্ট নিশ্চিত করে অ্যাক্সেস লিংক পেতে এই অর্ডার আইডি নিয়ে টেলিগ্রামে মেসেজ করুন।",
  ordNF:"এই ডিভাইস থেকে এই অর্ডার আইডি যাচাই করা গেল না।",
  ordNF2:"অনুগ্রহ করে অর্ডার আইডি নিয়ে টেলিগ্রামে মেসেজ করুন, আমরা নিজে দেখে জানাব।",

  /* ── ABOUT ── */
  abTitle:"আমাদের সম্পর্কে",
  abSub:"আমরা কারা এবং কেন এটা বানিয়েছি",
  abH1:"আমাদের গল্প",
  abP1:"দ্য মেথড মাফিয়ার শুরুটা হয়েছিল যেভাবে বেশিরভাগ কাজের জিনিস শুরু হয় — বিরক্তি থেকে।",
  abP2:"এক টাকা আয় করার আগেই সফটওয়্যার সাবস্ক্রিপশনে মাসে হাজার হাজার টাকা চলে যাচ্ছিল। যে কোর্সগুলো দুনিয়া বদলে দেওয়ার প্রতিশ্রুতি দেয়, তার দাম অনেকের মাসিক আয়ের চেয়ে বেশি — অথচ অর্ধেকই একই পুরনো বেসিক। আর সত্যিকারের কাজের তথ্যগুলো ছড়িয়ে ছিটিয়ে ছিল ইউটিউব কমেন্টে, ভুলে যাওয়া ব্লগ পোস্টে, আর এমন প্রাইভেট গ্রুপে যেখানে ঢুকতে হলে কাউকে চিনতে হয়।",
  abP3:"তাই আমরা জমাতে শুরু করলাম। যে মেথড সত্যিই কাজ করে, যে টুল ব্যবহারের যোগ্য, যে গাইড আসল কিছু শেখায় — সব সংরক্ষণ করলাম, পরীক্ষা করলাম, গুছিয়ে রাখলাম।",
  abP4:"ব্যক্তিগত সংগ্রহ হিসেবে যেটা শুরু হয়েছিল, সেটাই কমিউনিটি হয়ে গেল। আজ টেলিগ্রাম ও ফেসবুক মিলিয়ে ৫৬,০০০+ মানুষ আমাদের সাথে আছেন, আর হাজারো মানুষ প্রিমিয়াম লাইব্রেরিতে যোগ দিয়েছেন।",
  abH2:"আমরা যা বিশ্বাস করি",
  abB1:"<strong>শেখার সুযোগ বিশেষ কারো অধিকার হওয়া উচিত না।</strong> আপনি কোথায় থাকেন সেটা ঠিক করে দিতে পারে না আপনি শিখতে পারবেন কিনা।",
  abB2:"<strong>পরিমাণের চেয়ে মান।</strong> প্রতিটি মেথড গ্রুপে দেওয়ার আগে পরীক্ষা করা হয়।",
  abB3:"<strong>মিথ্যা প্রতিশ্রুতি নেই।</strong> রাতারাতি বড়লোক হওয়ার কথা আমরা বলি না। আমরা মেথড আর টুলস দিই — পরিশ্রমটা আপনার।",
  abB4:"<strong>কমিউনিটি সবার আগে।</strong> ভেতরের মানুষগুলোই এটাকে যোগ দেওয়ার মতো করে তোলে।",
  abH3:"আমরা যা নই",
  abNP:"এই বিষয়ে সৎ থাকতে চাই, কারণ এই জগতে অনেকেই থাকে না।",
  abN1:"আমরা রাতারাতি বড়লোক হওয়ার স্কিম নই।",
  abN2:"আমরা কোনো আয়ের গ্যারান্টি দিই না। যে দেয়, সে মিথ্যা বলছে।",
  abN3:"আমরা পরিশ্রমের বিকল্প নই। লাইব্রেরি শুরুর জায়গা, শেষ নয়।",
  abH4:"সংখ্যায়",
  abNum1:"<strong>৩০,০০০+</strong> ফেসবুক ফলোয়ার",
  abNum2:"<strong>২৬,০০০+</strong> পাবলিক টেলিগ্রাম মেম্বার",
  abNum3:"<strong>২,৯০০+</strong> সক্রিয় প্রিমিয়াম মেম্বার",
  abNum4:"<strong>১,০০০+</strong> বাছাই করা মেথড, টুলস ও গাইড",
  abNum5:"<strong>৫০-৭০+</strong> নতুন রিসোর্স প্রতি মাসে",
  abH5:"যোগাযোগ করুন",
  abGet:"আমরা সব পড়ি। প্রশ্ন, পরামর্শ বা অভিযোগ — যা-ই থাকুক, শুনতে চাই।",
  abBox:"এখনো জয়েন করতে প্রস্তুত নন? কোনো সমস্যা নেই। আমাদের ফ্রি পাবলিক চ্যানেল থেকে শুরু করুন, দেখুন আমরা যা শেয়ার করি তা আপনার কাজে লাগে কিনা। কোনো পেমেন্ট নেই, কোনো বাধ্যবাধকতা নেই।",
  abCta:"ফ্রি চ্যানেলে জয়েন করুন",
  abFree:"ফ্রি চ্যানেল:",
  abFb:"ফেসবুক:",
  abTg:"টেলিগ্রাম:",
  abMail:"ইমেইল:",

  /* ── TERMS ── */
  tmTitle:"শর্তাবলী",
  tmSub:"সর্বশেষ হালনাগাদ: আগস্ট ২০২৬",
  tmH1:"১. চুক্তি",
  tmP1:"এই ওয়েবসাইট ব্যবহার করে বা মেম্বারশিপ কিনে আপনি এই শর্তগুলোতে সম্মত হচ্ছেন। সম্মত না হলে অনুগ্রহ করে আমাদের সেবা ব্যবহার করবেন না।",
  tmH2:"২. আমরা যা দিই",
  tmP2:"দ্য মেথড মাফিয়া একটি ডিজিটাল রিসোর্স ও শেখার কমিউনিটি। মেম্বারশিপে আপনি একটি প্রাইভেট টেলিগ্রাম চ্যানেলে অ্যাক্সেস পাবেন যেখানে বাছাই করা মেথড, টুলস, গাইড ও শিক্ষামূলক উপকরণ থাকে।",
  tmP2b:"আমরা তথ্য ও রিসোর্সে অ্যাক্সেস দিই। তৃতীয় পক্ষের সেবা আমরা নিজে সরবরাহ করি না, এবং আমাদের উপকরণে উল্লেখিত কোনো ব্র্যান্ডের সাথে আমাদের কোনো সম্পর্ক বা অংশীদারিত্ব নেই।",
  tmH3:"৩. মেম্বারশিপ ও বিলিং",
  tmB1:"এন্ট্রি ফি-তে আপনার প্রথম মাসের অ্যাক্সেস অন্তর্ভুক্ত।",
  tmB2:"দ্বিতীয় মাস থেকে অ্যাক্সেস চালু রাখতে মাসিক ফি প্রযোজ্য।",
  tmB3:"মেম্বারশিপ স্বয়ংক্রিয়ভাবে রিনিউ হয় না। প্রতি মেয়াদে আপনি নিজে পেমেন্ট করবেন।",
  tmB4:"পেমেন্ট না পেলে চলতি মেয়াদ শেষ হওয়ার সাথে সাথে অ্যাক্সেস বন্ধ হয়ে যাবে।",
  tmB5:"দাম পরিবর্তন হতে পারে। পরিবর্তন কার্যকর হওয়ার আগে বর্তমান মেম্বারদের জানানো হবে।",
  tmH4:"৪. আপনার দায়িত্ব",
  tmP4:"আপনি সম্মত হচ্ছেন যে আপনি:",
  tmC1:"অর্ডারের সময় সঠিক তথ্য দেবেন",
  tmC2:"আপনার অ্যাক্সেস লিংক গোপন রাখবেন, কারো সাথে শেয়ার করবেন না",
  tmC3:"লিখিত অনুমতি ছাড়া আমাদের কনটেন্ট পুনঃপ্রকাশ বা বিতরণ করবেন না",
  tmC4:"আমাদের উপকরণ কোনো বেআইনি কাজে ব্যবহার করবেন না",
  tmC5:"অন্য মেম্বার ও স্টাফদের সাথে সম্মানজনক আচরণ করবেন",
  tmH5:"৫. অ্যাকাউন্ট বাতিল",
  tmP5:"নিচের কাজ করলে রিফান্ড ছাড়াই আপনার অ্যাক্সেস বাতিল হতে পারে:",
  tmD1:"অ-মেম্বারদের সাথে অ্যাক্সেস লিংক বা কনটেন্ট শেয়ার করা",
  tmD2:"অনুমতি ছাড়া আমাদের উপকরণ বিক্রির চেষ্টা করা",
  tmD3:"অন্য মেম্বার বা স্টাফদের হয়রানি করা",
  tmD4:"স্প্যাম বা প্রতারণামূলক কাজে কমিউনিটি ব্যবহার করা",
  tmH6:"৬. আয়ের কোনো গ্যারান্টি নেই",
  tmP6:"কোনো আয়, লাভ বা ব্যবসায়িক ফলাফল সম্পর্কে আমরা কোনো প্রতিশ্রুতি বা গ্যারান্টি দিই না। শেয়ার করা যেকোনো উদাহরণ শুধুই দৃষ্টান্তমূলক, সাধারণ ফলাফল নয়। আপনার ফলাফল সম্পূর্ণভাবে আপনার নিজের পরিশ্রম, দক্ষতা, বাজার পরিস্থিতি এবং আমাদের নিয়ন্ত্রণের বাইরে থাকা নানা বিষয়ের উপর নির্ভর করে।",
  tmH7:"৭. তৃতীয় পক্ষের সেবা",
  tmP7:"আমাদের উপকরণে তৃতীয় পক্ষের প্ল্যাটফর্ম ও টুলসের উল্লেখ থাকতে পারে। যেকোনো তৃতীয় পক্ষের সেবা ব্যবহার সেই সেবার নিজস্ব শর্ত দ্বারা নিয়ন্ত্রিত। সেগুলো মেনে চলার দায়িত্ব আপনার। তৃতীয় পক্ষের সেবা ব্যবহারের ফলে যা কিছু ঘটে তার জন্য আমরা দায়ী নই।",
  tmH8:"৮. মেধাস্বত্ব",
  tmP8:"আমাদের তৈরি সব মৌলিক কনটেন্ট, ব্র্যান্ডিং, ডিজাইন ও উপকরণ দ্য মেথড মাফিয়ার সম্পত্তি। নিজের শেখার জন্য ব্যবহার করতে পারবেন, কিন্তু বাণিজ্যিকভাবে পুনরুৎপাদন বা বিতরণ করতে পারবেন না।",
  tmH9:"৯. দায়বদ্ধতার সীমা",
  tmP9:"আমাদের সেবা যেমন আছে তেমনই দেওয়া হয়। আইন যতটুকু অনুমতি দেয়, আমাদের সেবা ব্যবহারের ফলে সৃষ্ট কোনো পরোক্ষ বা আনুষঙ্গিক ক্ষতির জন্য আমরা দায়ী নই। আমাদের সর্বোচ্চ দায় গত তিন মাসে আপনি যা পরিশোধ করেছেন তার মধ্যেই সীমাবদ্ধ।",
  tmH10:"১০. শর্তে পরিবর্তন",
  tmP10:"আমরা এই শর্তগুলো হালনাগাদ করতে পারি। উল্লেখযোগ্য পরিবর্তন আমাদের চ্যানেলে ঘোষণা করা হবে। পরিবর্তনের পরেও ব্যবহার চালিয়ে গেলে ধরে নেওয়া হবে আপনি নতুন শর্ত মেনে নিয়েছেন।",
  tmH11:"১১. প্রযোজ্য আইন",
  tmP11:"এই শর্তাবলী বাংলাদেশের আইন দ্বারা নিয়ন্ত্রিত।",
  tmH12:"১২. যোগাযোগ",
  tmP12:"শর্তাবলী নিয়ে প্রশ্ন? ইমেইল করুন",
  tmP12b:"অথবা টেলিগ্রামে মেসেজ করুন",
  tmP12c:"।",

  /* ── PRIVACY ── */
  prTitle:"গোপনীয়তা নীতি",
  prSub:"সর্বশেষ হালনাগাদ: আগস্ট ২০২৬",
  prH1:"১. ভূমিকা",
  prP1:"এই নীতিতে বলা আছে আমরা কী তথ্য সংগ্রহ করি, কেন করি এবং তা দিয়ে কী করি। ইচ্ছে করেই এটা ছোট ও সহজ রেখেছি, কারণ আপনার আসলেই এটা পড়তে পারা উচিত।",
  prH2:"২. আমরা যা সংগ্রহ করি",
  prP2a:"<strong>আপনি যা দেন:</strong>",
  prG1:"নাম",
  prG2:"ইমেইল ঠিকানা",
  prG3:"টেলিগ্রাম ইউজারনেম",
  prG4:"পেমেন্ট রেফারেন্স বা ট্রানজেকশন আইডি (প্রমাণ পাঠানোর সময়)",
  prP2b:"<strong>স্বয়ংক্রিয়ভাবে যা সংগ্রহ হয়:</strong>",
  prA1:"কোন পেজ দেখেছেন ও কতক্ষণ ছিলেন",
  prA2:"আনুমানিক অবস্থান (দেশ বা শহর পর্যায়ে)",
  prA3:"ডিভাইস ও ব্রাউজারের ধরন",
  prA4:"কোথা থেকে এসেছেন, বিজ্ঞাপন ক্যাম্পেইনের তথ্যসহ",
  prH3:"৩. কেন সংগ্রহ করি",
  prW1:"আপনার অর্ডার প্রক্রিয়া করতে ও অ্যাক্সেস দিতে",
  prW2:"মেম্বারশিপ নিয়ে আপনার সাথে যোগাযোগ করতে",
  prW3:"রিনিউয়াল রিমাইন্ডার পাঠাতে",
  prW4:"কোন মার্কেটিং কাজ করছে বুঝতে, যাতে বাজেট বুদ্ধিমানের মতো খরচ হয়",
  prW5:"সাইট ও সেবার মান উন্নত করতে",
  prH5:"৪. আমরা যা করি না",
  prN1:"আপনার ব্যক্তিগত তথ্য কারো কাছে বিক্রি করি না।",
  prN2:"আপনার তথ্য অন্য মেম্বারদের সাথে শেয়ার করি না।",
  prN3:"আপনার পেমেন্ট তথ্য, পিন, ওটিপি বা কার্ডের তথ্য সংরক্ষণ করি না। আমরা এগুলো কখনো চাইও না।",
  prN4:"যারা আমাদের সাথে যোগাযোগ করেননি তাদের অযাচিত মার্কেটিং মেসেজ পাঠাই না।",
  prH6:"৫. কতদিন তথ্য রাখি",
  prP6:"মেম্বারশিপ সক্রিয় থাকা পর্যন্ত এবং হিসাব সংরক্ষণের জন্য এরপর যুক্তিসঙ্গত সময় পর্যন্ত অর্ডারের তথ্য রাখা হয়। আপনি যেকোনো সময় মুছে ফেলার অনুরোধ করতে পারেন।",
  prH7:"৬. আপনার অধিকার",
  prP7:"আপনি আমাদের বলতে পারেন:",
  prR1:"আপনার সম্পর্কে কী তথ্য আছে তা দেখাতে",
  prR2:"ভুল কিছু থাকলে সংশোধন করতে",
  prR3:"আপনার তথ্য মুছে ফেলতে",
  prR4:"আপনাকে মেসেজ পাঠানো বন্ধ করতে",
  prP7b:"এসব অনুরোধ করতে ইমেইল করুন",
  prH8:"৭. কুকিজ",
  prP8:"বিশ্লেষণ ও বিজ্ঞাপন পরিমাপের জন্য আমরা কুকিজ ও অনুরূপ প্রযুক্তি ব্যবহার করি। ব্রাউজার সেটিংসে কুকিজ বন্ধ করতে পারেন, তবে সাইটের কিছু অংশ ঠিকমতো কাজ নাও করতে পারে।",
  prH9:"৮. নিরাপত্তা",
  prP9:"আমরা HTTPS এনক্রিপশন ব্যবহার করি এবং অর্ডারের তথ্যে অ্যাক্সেস সীমিত রাখি। কোনো সিস্টেমই শতভাগ নিরাপদ নয়, তবে আপনার তথ্য রক্ষায় আমরা যুক্তিসঙ্গত ব্যবস্থা নিই।",
  prH10:"৯. শিশু",
  prP10:"আমাদের সেবা ১৮ বছরের নিচে কারো জন্য নয়। আমরা জেনেশুনে অপ্রাপ্তবয়স্কদের তথ্য সংগ্রহ করি না।",
  prH11:"১০. পরিবর্তন",
  prP11:"এই নীতিতে উল্লেখযোগ্য পরিবর্তন করলে আমাদের চ্যানেলে ঘোষণা করব।",
  prH12:"১১. যোগাযোগ",
  prP12:"গোপনীয়তা নিয়ে প্রশ্ন? ইমেইল করুন",
  prP12b:"অথবা মেসেজ করুন",

  /* ── REFUND ── */
  rfTitle:"রিফান্ড নীতি",
  rfSub:"সর্বশেষ হালনাগাদ: আগস্ট ২০২৬",
  rfShort:"<strong>সংক্ষেপে:</strong> আমাদের দিক থেকে কিছু ভুল হলে আমরা টাকা ফেরত দিই। কিন্তু লাইব্রেরিতে ঢুকে দেখার পর শুধু মত বদলালে সাধারণত পারি না — কারণ ডিজিটাল কনটেন্ট একবার দেখে ফেললে ফেরত দেওয়া যায় না।",
  rfH1:"১. যখন পুরো টাকা ফেরত পাবেন",
  rfP1:"নিচের ক্ষেত্রে আমরা পুরো টাকা ফেরত দিই:",
  rfY1:"পেমেন্ট করেছেন কিন্তু অ্যাক্সেস লিংক পাননি, এবং ৪৮ ঘণ্টার মধ্যে আমরা সমাধান করতে পারিনি",
  rfY2:"একই মেয়াদের জন্য দুইবার টাকা কাটা হয়েছে",
  rfY3:"ভুল করে বেশি টাকা পাঠিয়েছেন এবং এখনো চ্যানেলে ঢোকেননি",
  rfY4:"আপনার পরিশোধিত মেয়াদের মধ্যে আমাদের সেবা স্থায়ীভাবে বন্ধ হয়ে গেছে",
  rfH2:"২. যখন রিফান্ড দিতে পারি না",
  rfP2:"নিচের ক্ষেত্রে রিফান্ড দেওয়া সম্ভব নয়:",
  rfN1:"আপনি ইতিমধ্যে চ্যানেলে ঢুকে কনটেন্ট দেখে ফেলেছেন",
  rfN2:"অ্যাক্সেস পাওয়ার পর মত বদলেছেন",
  rfN3:"নির্দিষ্ট আয়ের আশা করেছিলেন যা হয়নি",
  rfN4:"শর্ত ভাঙার কারণে আপনার অ্যাক্সেস বাতিল হয়েছে",
  rfN5:"আপনি যে তৃতীয় পক্ষের সেবা সম্পর্কে জেনেছেন সেটি কাজ করা বন্ধ করেছে — ওই সেবাগুলো আমাদের নিয়ন্ত্রণে নেই",
  rfN6:"পেমেন্টের পর ৭ দিনের বেশি সময় পার হয়ে গেছে",
  rfP2b:"ডিজিটাল পণ্যের ক্ষেত্রে এটাই স্বাভাবিক নিয়ম। লাইব্রেরি একবার দেখে ফেললে সেটা আর না-দেখা করা যায় না।",
  rfH3:"৩. আংশিক রিফান্ড",
  rfP3:"মেয়াদের মাঝখানে সত্যিকারের কোনো সমস্যা হলে আমরা আংশিক রিফান্ড দিতে পারি বা মেম্বারশিপের মেয়াদ বাড়িয়ে দিতে পারি। প্রতিটি ঘটনা আলাদাভাবে দেখি এবং ন্যায্য থাকার চেষ্টা করি।",
  rfH4:"৪. রিফান্ড চাওয়ার নিয়ম",
  rfS1:"পেমেন্টের ৭ দিনের মধ্যে টেলিগ্রামে মেসেজ করুন",
  rfS2:"অর্ডার আইডি উল্লেখ করুন",
  rfS3:"কী সমস্যা হয়েছে বুঝিয়ে বলুন",
  rfS4:"পেমেন্টের প্রমাণ সংযুক্ত করুন",
  rfH5:"৫. প্রক্রিয়ার সময়",
  rfT1:"<strong>পর্যালোচনা:</strong> অনুরোধের ৪৮ ঘণ্টার মধ্যে",
  rfT2:"<strong>অনুমোদিত রিফান্ড:</strong> ৩ থেকে ৭ কর্মদিবসের মধ্যে পাঠানো হয়",
  rfT3:"<strong>মাধ্যম:</strong> যে অ্যাকাউন্ট থেকে পেমেন্ট করেছেন সেখানেই ফেরত",
  rfH6:"৬. মেম্বারশিপ বাতিল",
  rfP6:"বাতিল করার কিছু নেই। মেম্বারশিপ স্বয়ংক্রিয়ভাবে রিনিউ হয় না — পরের মাসের টাকা না দিলে চলতি মেয়াদ শেষ হলেই অ্যাক্সেস বন্ধ হয়ে যাবে। কোনো বাতিল ফি নেই, আগে জানানোরও দরকার নেই।",
  rfH7:"৭. চার্জব্যাক",
  rfP7:"চার্জব্যাক বা ডিসপিউট করার আগে অনুগ্রহ করে আমাদের সাথে কথা বলুন। বেশিরভাগ সমস্যাই ভুল বোঝাবুঝি, যা কয়েক মিনিটে সমাধান হয়ে যায়। আমাদের না জানিয়ে ডিসপিউট করলে কমিউনিটি থেকে স্থায়ীভাবে বাদ দেওয়া হবে।",
  rfH8:"৮. আমাদের অঙ্গীকার",
  rfP8:"অসন্তুষ্ট কাউকে টাকা ফেরত দেওয়া আমাদের কাছে ভালো, তিক্ততা রেখে টাকা রাখার চেয়ে। সত্যিই ঠকেছেন মনে হলে আমাদের বলুন। আমরা শুনব।",
  rfBox:"এই নীতি নিয়ে প্রশ্ন? মেসেজ করুন",
  rfBox2:"অথবা ইমেইল করুন"
},

/* ─────────────── हिन्दी ─────────────── */
hi: {
  back:"होम पर वापस",

  /* ── PAYMENT ── */
  payTitle:"पेमेंट निर्देश",
  paySub:"मेंबरशिप का भुगतान कैसे पूरा करें",
  payNote:"<strong>महत्वपूर्ण:</strong> धोखाधड़ी से आपको और हमें बचाने के लिए हम पेमेंट डिटेल्स सार्वजनिक नहीं करते। ऑर्डर करने के बाद सब कुछ सीधे टेलीग्राम पर बताया जाता है।",
  payH1:"यह कैसे काम करता है",
  payS1t:"ऑर्डर करें",
  payS1d:"होमपेज के फॉर्म में अपना नाम, ईमेल और टेलीग्राम यूजरनेम भरें। आपको एक ऑर्डर आईडी मिलेगी।",
  payS2t:"टेलीग्राम पर मैसेज करें",
  payS2d:"सबमिट करने के बाद आप हमारे सपोर्ट अकाउंट पर पहुंच जाएंगे। ऑर्डर आईडी भेजें, हम पेमेंट डिटेल्स बता देंगे।",
  payS3t:"भुगतान करें",
  payS3d:"आपने जो मेथड चुना है उससे राशि भेजें। लेनदेन का स्क्रीनशॉट रख लें।",
  payS4t:"प्रमाण भेजें",
  payS4d:"स्क्रीनशॉट और ट्रांजैक्शन आईडी टेलीग्राम पर भेजें। हर पेमेंट हम खुद जांचते हैं।",
  payS5t:"एक्सेस पाएं",
  payS5d:"पुष्टि होते ही हम एक प्राइवेट वन-टाइम इनवाइट लिंक भेजते हैं। आमतौर पर 30 मिनट से 3 घंटे लगते हैं।",
  payH2:"स्वीकृत पेमेंट मेथड",
  payH3:"कीमत",
  payEntry:"एंट्री (पहला महीना):",
  payMonthly:"मासिक (दूसरे महीने से):",
  payH4:"जरूरी बातें",
  payN1:"सिर्फ उन्हीं डिटेल्स पर पेमेंट करें जो हम टेलीग्राम पर देते हैं। किसी और के दिए नंबर पर कभी भरोसा न करें।",
  payN2:"एक्सेस मिलने तक अपनी ट्रांजैक्शन आईडी संभाल कर रखें।",
  payN3:"टेलीग्राम यूजरनेम सही होना चाहिए, वरना हम इनवाइट नहीं भेज पाएंगे।",
  payN4:"हम कभी आपका पिन, ओटीपी या पासवर्ड नहीं मांगते। जो मांगे, वो ठग है।",
  payHelp:"मदद चाहिए? मैसेज करें",
  payCta:"ऑर्डर करें",

  /* ── ORDER STATUS ── */
  ordTitle:"ऑर्डर स्टेटस",
  ordSub:"देखें आपका ऑर्डर किस स्थिति में है",
  ordFind:"अपना ऑर्डर खोजें",
  ordFindSub:"आपको जो ऑर्डर आईडी मिली है वो डालें",
  ordLbl:"ऑर्डर आईडी",
  ordBtn:"स्टेटस देखें",
  ordH1:"स्टेटस का मतलब",
  ordSt1:"<strong>Pending</strong> — ऑर्डर मिल गया है, पर पेमेंट अभी नहीं मिला या पुष्टि नहीं हुई।",
  ordSt2:"<strong>Verifying</strong> — पेमेंट का प्रमाण मिल गया है, जांच चल रही है।",
  ordSt3:"<strong>Active</strong> — पेमेंट की पुष्टि हो गई, टेलीग्राम पर इनवाइट लिंक भेज दिया गया है।",
  ordSt4:"<strong>Expired</strong> — मेंबरशिप की अवधि खत्म। दोबारा एक्सेस के लिए रिन्यू करें।",
  ordH2:"ऑर्डर आईडी खो गई?",
  ordLost:"कोई बात नहीं। ऑर्डर करते समय जो ईमेल या टेलीग्राम यूजरनेम दिया था वो टेलीग्राम पर भेजें, हम ढूंढ देंगे।",
  ordHelp:"ऑर्डर से जुड़ी किसी भी समस्या के लिए संपर्क करें",
  ordHelp2:"— आमतौर पर कुछ घंटों में जवाब देते हैं।",
  ordErr:"कृपया अपनी ऑर्डर आईडी डालें।",
  ordFound:"ऑर्डर मिल गया:",
  ordStatus:"स्टेटस:",
  ordSubmitted:"सबमिट हो गया",
  ordFoundMsg:"आपका ऑर्डर मिल गया है। पेमेंट की पुष्टि और एक्सेस लिंक के लिए यह ऑर्डर आईडी लेकर टेलीग्राम पर मैसेज करें।",
  ordNF:"इस डिवाइस से यह ऑर्डर आईडी सत्यापित नहीं हो सकी।",
  ordNF2:"कृपया ऑर्डर आईडी लेकर टेलीग्राम पर मैसेज करें, हम खुद जांच कर बताएंगे।",

  /* ── ABOUT ── */
  abTitle:"हमारे बारे में",
  abSub:"हम कौन हैं और यह क्यों बनाया",
  abH1:"हमारी कहानी",
  abP1:"द मेथड माफिया की शुरुआत वैसे ही हुई जैसे ज्यादातर काम की चीज़ें शुरू होती हैं — झुंझलाहट से।",
  abP2:"कुछ भी कमाने से पहले ही सॉफ्टवेयर सब्सक्रिप्शन पर हर महीने हजारों खर्च हो रहे थे। जो कोर्स दुनिया बदलने का वादा करते हैं, उनकी कीमत कई लोगों की महीने की कमाई से ज्यादा है — और आधे तो वही पुरानी बेसिक बातें दोहराते हैं। असली काम की जानकारी यूट्यूब कमेंट, भूले-बिसरे ब्लॉग पोस्ट और ऐसे प्राइवेट ग्रुप में बिखरी पड़ी थी जहां घुसने के लिए किसी को जानना पड़ता है।",
  abP3:"तो हमने जमा करना शुरू किया। जो मेथड सच में काम करता है, जो टूल इस्तेमाल के लायक है, जो गाइड कुछ असली सिखाती है — सब सहेजा, परखा और व्यवस्थित किया।",
  abP4:"जो निजी संग्रह के तौर पर शुरू हुआ था वो कम्युनिटी बन गया। आज टेलीग्राम और फेसबुक मिलाकर 56,000+ लोग हमसे जुड़े हैं, और हजारों प्रीमियम लाइब्रेरी में शामिल हो चुके हैं।",
  abH2:"हम क्या मानते हैं",
  abB1:"<strong>सीखने का मौका किसी की विशेष सुविधा नहीं होनी चाहिए।</strong> आप कहां रहते हैं इससे यह तय नहीं होना चाहिए कि आप सीख सकते हैं या नहीं।",
  abB2:"<strong>मात्रा से ज्यादा गुणवत्ता।</strong> हर मेथड ग्रुप में डालने से पहले परखा जाता है।",
  abB3:"<strong>झूठे वादे नहीं।</strong> हम रातों-रात अमीर बनाने की बात नहीं करते। हम मेथड और टूल्स देते हैं — मेहनत आपकी।",
  abB4:"<strong>कम्युनिटी सबसे पहले।</strong> अंदर के लोग ही इसे जुड़ने लायक बनाते हैं।",
  abH3:"हम क्या नहीं हैं",
  abNP:"इस बारे में ईमानदार रहना चाहते हैं, क्योंकि इस क्षेत्र में बहुत लोग नहीं होते।",
  abN1:"हम रातों-रात अमीर बनाने वाली स्कीम नहीं हैं।",
  abN2:"हम किसी आय की गारंटी नहीं देते। जो देता है, वो झूठ बोल रहा है।",
  abN3:"हम मेहनत का विकल्प नहीं हैं। लाइब्रेरी शुरुआत है, अंत नहीं।",
  abH4:"आंकड़ों में",
  abNum1:"<strong>30,000+</strong> फेसबुक फॉलोअर",
  abNum2:"<strong>26,000+</strong> पब्लिक टेलीग्राम मेंबर",
  abNum3:"<strong>2,900+</strong> सक्रिय प्रीमियम मेंबर",
  abNum4:"<strong>1,000+</strong> चुनिंदा मेथड, टूल्स और गाइड",
  abNum5:"<strong>50-70+</strong> नए रिसोर्स हर महीने",
  abH5:"संपर्क करें",
  abGet:"हम सब पढ़ते हैं। सवाल, सुझाव या शिकायत — जो भी हो, सुनना चाहते हैं।",
  abBox:"अभी जुड़ने को तैयार नहीं? कोई बात नहीं। हमारे फ्री पब्लिक चैनल से शुरू करें और देखें कि जो हम शेयर करते हैं वो आपके काम का है या नहीं। कोई पेमेंट नहीं, कोई बाध्यता नहीं।",
  abCta:"फ्री चैनल जॉइन करें",
  abFree:"फ्री चैनल:",
  abFb:"फेसबुक:",
  abTg:"टेलीग्राम:",
  abMail:"ईमेल:",

  /* ── TERMS ── */
  tmTitle:"नियम एवं शर्तें",
  tmSub:"अंतिम अपडेट: अगस्त 2026",
  tmH1:"1. समझौता",
  tmP1:"इस वेबसाइट का उपयोग करके या मेंबरशिप खरीदकर आप इन शर्तों से सहमत होते हैं। सहमत न हों तो कृपया हमारी सेवा का उपयोग न करें।",
  tmH2:"2. हम क्या देते हैं",
  tmP2:"द मेथड माफिया एक डिजिटल रिसोर्स और लर्निंग कम्युनिटी है। मेंबरशिप से आपको एक प्राइवेट टेलीग्राम चैनल का एक्सेस मिलता है जिसमें चुनिंदा मेथड, टूल्स, गाइड और शैक्षिक सामग्री होती है।",
  tmP2b:"हम जानकारी और रिसोर्स तक पहुंच देते हैं। तीसरे पक्ष की सेवाएं हम खुद प्रदान नहीं करते, और हमारी सामग्री में उल्लिखित किसी ब्रांड से हमारा कोई संबंध या साझेदारी नहीं है।",
  tmH3:"3. मेंबरशिप और बिलिंग",
  tmB1:"एंट्री फीस में आपका पहला महीना शामिल है।",
  tmB2:"दूसरे महीने से एक्सेस बनाए रखने के लिए मासिक शुल्क लागू होता है।",
  tmB3:"मेंबरशिप अपने आप रिन्यू नहीं होती। हर अवधि का भुगतान आप खुद करते हैं।",
  tmB4:"भुगतान न मिलने पर चालू अवधि खत्म होते ही एक्सेस बंद हो जाता है।",
  tmB5:"कीमतें बदल सकती हैं। बदलाव लागू होने से पहले मौजूदा मेंबर्स को सूचित किया जाएगा।",
  tmH4:"4. आपकी जिम्मेदारियां",
  tmP4:"आप सहमत हैं कि आप:",
  tmC1:"ऑर्डर करते समय सही जानकारी देंगे",
  tmC2:"अपना एक्सेस लिंक निजी रखेंगे, किसी से साझा नहीं करेंगे",
  tmC3:"लिखित अनुमति के बिना हमारी सामग्री दोबारा प्रकाशित या वितरित नहीं करेंगे",
  tmC4:"हमारी सामग्री का किसी गैरकानूनी काम में उपयोग नहीं करेंगे",
  tmC5:"अन्य मेंबर्स और स्टाफ के साथ सम्मानजनक व्यवहार करेंगे",
  tmH5:"5. अकाउंट समाप्ति",
  tmP5:"निम्न स्थितियों में बिना रिफंड आपका एक्सेस हटाया जा सकता है:",
  tmD1:"गैर-मेंबर्स के साथ एक्सेस लिंक या सामग्री साझा करना",
  tmD2:"बिना अनुमति हमारी सामग्री बेचने की कोशिश करना",
  tmD3:"अन्य मेंबर्स या स्टाफ को परेशान करना",
  tmD4:"स्पैम या धोखाधड़ी के लिए कम्युनिटी का उपयोग करना",
  tmH6:"6. आय की कोई गारंटी नहीं",
  tmP6:"किसी आय, लाभ या व्यावसायिक परिणाम के बारे में हम कोई वादा या गारंटी नहीं देते। साझा किए गए उदाहरण केवल उदाहरण हैं, सामान्य परिणाम नहीं। आपके परिणाम पूरी तरह आपकी मेहनत, कौशल, बाजार की स्थिति और हमारे नियंत्रण से बाहर के कारकों पर निर्भर करते हैं।",
  tmH7:"7. तीसरे पक्ष की सेवाएं",
  tmP7:"हमारी सामग्री में तीसरे पक्ष के प्लेटफॉर्म और टूल्स का उल्लेख हो सकता है। किसी भी तीसरे पक्ष की सेवा का उपयोग उस सेवा की अपनी शर्तों से नियंत्रित होता है। उनका पालन करना आपकी जिम्मेदारी है। तीसरे पक्ष की सेवाओं के उपयोग से होने वाली किसी बात के लिए हम जिम्मेदार नहीं हैं।",
  tmH8:"8. बौद्धिक संपदा",
  tmP8:"हमारी बनाई सभी मौलिक सामग्री, ब्रांडिंग, डिज़ाइन और सामग्री द मेथड माफिया की है। आप इसे अपने सीखने के लिए उपयोग कर सकते हैं, पर व्यावसायिक रूप से पुनरुत्पादित या वितरित नहीं कर सकते।",
  tmH9:"9. दायित्व की सीमा",
  tmP9:"हमारी सेवा जैसी है वैसी दी जाती है। कानून जितनी अनुमति देता है, हमारी सेवा के उपयोग से होने वाले किसी अप्रत्यक्ष या आनुषंगिक नुकसान के लिए हम जिम्मेदार नहीं हैं। हमारा कुल दायित्व पिछले तीन महीनों में आपके द्वारा भुगतान की गई राशि तक सीमित है।",
  tmH10:"10. शर्तों में बदलाव",
  tmP10:"हम इन शर्तों को अपडेट कर सकते हैं। महत्वपूर्ण बदलाव हमारे चैनलों पर घोषित किए जाएंगे। बदलाव के बाद उपयोग जारी रखने का मतलब है आप नई शर्तें स्वीकार करते हैं।",
  tmH11:"11. लागू कानून",
  tmP11:"ये शर्तें बांग्लादेश के कानूनों द्वारा नियंत्रित हैं।",
  tmH12:"12. संपर्क",
  tmP12:"इन शर्तों के बारे में सवाल? ईमेल करें",
  tmP12b:"या टेलीग्राम पर मैसेज करें",
  tmP12c:"।",

  /* ── PRIVACY ── */
  prTitle:"गोपनीयता नीति",
  prSub:"अंतिम अपडेट: अगस्त 2026",
  prH1:"1. परिचय",
  prP1:"यह नीति बताती है कि हम क्या जानकारी इकट्ठा करते हैं, क्यों करते हैं और उसका क्या करते हैं। इसे जानबूझकर छोटा और सरल रखा है, क्योंकि आपको इसे वाकई पढ़ पाना चाहिए।",
  prH2:"2. हम क्या इकट्ठा करते हैं",
  prP2a:"<strong>जो आप देते हैं:</strong>",
  prG1:"नाम",
  prG2:"ईमेल पता",
  prG3:"टेलीग्राम यूजरनेम",
  prG4:"पेमेंट रेफरेंस या ट्रांजैक्शन आईडी (प्रमाण भेजते समय)",
  prP2b:"<strong>जो अपने आप इकट्ठा होता है:</strong>",
  prA1:"कौन से पेज देखे और कितनी देर रुके",
  prA2:"अनुमानित स्थान (देश या शहर स्तर)",
  prA3:"डिवाइस और ब्राउज़र का प्रकार",
  prA4:"कहां से आए, विज्ञापन कैंपेन की जानकारी सहित",
  prH3:"3. क्यों इकट्ठा करते हैं",
  prW1:"आपका ऑर्डर प्रोसेस करने और एक्सेस देने के लिए",
  prW2:"मेंबरशिप के बारे में आपसे संपर्क करने के लिए",
  prW3:"रिन्यूअल रिमाइंडर भेजने के लिए",
  prW4:"यह समझने के लिए कि कौन सी मार्केटिंग काम कर रही है, ताकि बजट समझदारी से खर्च हो",
  prW5:"साइट और सेवा को बेहतर बनाने के लिए",
  prH5:"4. हम क्या नहीं करते",
  prN1:"हम आपकी निजी जानकारी किसी को नहीं बेचते।",
  prN2:"हम आपका डेटा अन्य मेंबर्स के साथ साझा नहीं करते।",
  prN3:"हम आपके पेमेंट क्रेडेंशियल, पिन, ओटीपी या कार्ड डिटेल्स स्टोर नहीं करते। हम ये कभी मांगते भी नहीं।",
  prN4:"जिन लोगों ने हमसे संपर्क नहीं किया उन्हें अनचाहे मार्केटिंग मैसेज नहीं भेजते।",
  prH6:"5. डेटा कितने समय रखते हैं",
  prP6:"मेंबरशिप सक्रिय रहने तक और उसके बाद लेखांकन के लिए उचित अवधि तक ऑर्डर रिकॉर्ड रखे जाते हैं। आप कभी भी हटाने का अनुरोध कर सकते हैं।",
  prH7:"6. आपके अधिकार",
  prP7:"आप हमसे कह सकते हैं:",
  prR1:"आपके बारे में क्या डेटा है वो दिखाएं",
  prR2:"कुछ गलत हो तो सुधारें",
  prR3:"आपका डेटा हटा दें",
  prR4:"आपको मैसेज भेजना बंद करें",
  prP7b:"इनमें से कोई अनुरोध करने के लिए ईमेल करें",
  prH8:"7. कुकीज़",
  prP8:"विश्लेषण और विज्ञापन मापन के लिए हम कुकीज़ और समान तकनीक का उपयोग करते हैं। ब्राउज़र सेटिंग्स में कुकीज़ बंद कर सकते हैं, हालांकि साइट के कुछ हिस्से ठीक से काम नहीं कर सकते।",
  prH9:"8. सुरक्षा",
  prP9:"हम HTTPS एन्क्रिप्शन का उपयोग करते हैं और ऑर्डर डेटा तक पहुंच सीमित रखते हैं। कोई भी सिस्टम पूरी तरह सुरक्षित नहीं होता, पर आपकी जानकारी की रक्षा के लिए हम उचित कदम उठाते हैं।",
  prH10:"9. बच्चे",
  prP10:"हमारी सेवा 18 साल से कम उम्र के किसी के लिए नहीं है। हम जानबूझकर नाबालिगों की जानकारी इकट्ठा नहीं करते।",
  prH11:"10. बदलाव",
  prP11:"अगर हम इस नीति में कोई महत्वपूर्ण बदलाव करते हैं तो अपने चैनलों पर घोषणा करेंगे।",
  prH12:"11. संपर्क",
  prP12:"गोपनीयता से जुड़े सवाल? ईमेल करें",
  prP12b:"या मैसेज करें",

  /* ── REFUND ── */
  rfTitle:"रिफंड नीति",
  rfSub:"अंतिम अपडेट: अगस्त 2026",
  rfShort:"<strong>संक्षेप में:</strong> हमारी तरफ से कुछ गलत हो तो हम पैसे लौटाते हैं। पर लाइब्रेरी देख लेने के बाद सिर्फ मन बदलने पर आमतौर पर नहीं लौटा सकते — क्योंकि डिजिटल सामग्री एक बार देख लेने के बाद वापस नहीं की जा सकती।",
  rfH1:"1. पूरा रिफंड कब मिलेगा",
  rfP1:"निम्न स्थितियों में हम पूरा पैसा लौटाते हैं:",
  rfY1:"आपने भुगतान किया पर एक्सेस लिंक नहीं मिला, और 48 घंटे में हम हल नहीं कर पाए",
  rfY2:"एक ही अवधि के लिए दो बार पैसे कटे",
  rfY3:"गलती से गलत राशि भेजी और अभी तक चैनल में नहीं गए",
  rfY4:"आपकी भुगतान की गई अवधि के दौरान हमारी सेवा स्थायी रूप से बंद हो गई",
  rfH2:"2. रिफंड कब नहीं दे सकते",
  rfP2:"निम्न स्थितियों में रिफंड संभव नहीं:",
  rfN1:"आप चैनल में जाकर सामग्री देख चुके हैं",
  rfN2:"एक्सेस मिलने के बाद मन बदल गया",
  rfN3:"आपने कोई खास आय की उम्मीद की थी जो नहीं हुई",
  rfN4:"शर्तें तोड़ने के कारण आपका एक्सेस हटाया गया",
  rfN5:"आपने जिस तीसरे पक्ष की सेवा के बारे में जाना वो काम करना बंद कर दे — वे सेवाएं हमारे नियंत्रण में नहीं",
  rfN6:"भुगतान को 7 दिन से ज्यादा हो गए",
  rfP2b:"डिजिटल उत्पादों के लिए यह सामान्य नियम है। लाइब्रेरी एक बार देख लेने के बाद उसे अनदेखा नहीं किया जा सकता।",
  rfH3:"3. आंशिक रिफंड",
  rfP3:"अवधि के बीच में कोई वास्तविक समस्या आए तो हम आंशिक रिफंड दे सकते हैं या मेंबरशिप बढ़ा सकते हैं। हर मामले को अलग से देखते हैं और निष्पक्ष रहने की कोशिश करते हैं।",
  rfH4:"4. रिफंड कैसे मांगें",
  rfS1:"भुगतान के 7 दिन के भीतर टेलीग्राम पर मैसेज करें",
  rfS2:"अपनी ऑर्डर आईडी बताएं",
  rfS3:"क्या गलत हुआ समझाएं",
  rfS4:"भुगतान का प्रमाण संलग्न करें",
  rfH5:"5. प्रक्रिया का समय",
  rfT1:"<strong>समीक्षा:</strong> अनुरोध के 48 घंटे के भीतर",
  rfT2:"<strong>स्वीकृत रिफंड:</strong> 3 से 7 कार्यदिवसों में भेजा जाता है",
  rfT3:"<strong>माध्यम:</strong> जिस अकाउंट से भुगतान किया उसी में वापस",
  rfH6:"6. मेंबरशिप रद्द करना",
  rfP6:"रद्द करने को कुछ है ही नहीं। मेंबरशिप अपने आप रिन्यू नहीं होती — अगले महीने का भुगतान न करें तो चालू अवधि खत्म होते ही एक्सेस बंद हो जाएगा। कोई रद्दीकरण शुल्क नहीं, पहले बताने की भी जरूरत नहीं।",
  rfH7:"7. चार्जबैक",
  rfP7:"चार्जबैक या विवाद दर्ज करने से पहले कृपया हमसे बात करें। ज्यादातर समस्याएं गलतफहमी होती हैं जो मिनटों में सुलझ जाती हैं। हमसे संपर्क किए बिना विवाद दर्ज करने पर कम्युनिटी से स्थायी रूप से हटा दिया जाएगा।",
  rfH8:"8. हमारी प्रतिबद्धता",
  rfP8:"किसी नाराज़ ग्राहक को पैसे लौटा देना हमें बेहतर लगता है, बजाय कड़वाहट के साथ पैसे रखने के। अगर आपको लगता है कि आपको सच में गुमराह किया गया, हमें बताएं। हम सुनेंगे।",
  rfBox:"इस नीति के बारे में सवाल? मैसेज करें",
  rfBox2:"या ईमेल करें"
}

};
